//! Cross-repo delivery wire-format integration tests.
//!
//! These tests verify that LimeNet can deserialize JSON emitted by the
//! meta-agent Python delivery fixture exporter, confirming that the
//! shared Phase 2B wire contract is honored by both repos.
//!
//! The JSON fixtures live in `.state/artifacts/delivery_wire/` and are
//! generated by `.state/artifacts/export_delivery_fixtures.py`.
//!
//! ## DeliveryStatus — the shared alignment point
//!
//! Both repos agree on 5 delivery status variants: proposed, accepted,
//! needs_revision, rejected, superseded.  The Python `delivery_status`
//! field serializes as one of these 5 snake_case strings, and LimeNet's
//! `DeliveryStatus` enum deserializes them correctly.
//!
//! ## DeliveryPackage — shared Phase 2B wire shape
//!
//! Both repos now use the same field names for the delivery package
//! wire shape: `package_id`, `delivery_contract_id`, `result_summary`,
//! `evidence_refs`, `review_surface_refs`, `open_risks`,
//! `unresolved_items`, `recommended_next_action`, `delivery_status`,
//! `trace_context`.  Python-emitted delivery payloads deserialize and
//! validate successfully in Rust.
//!
//! ## EvidenceRollup — shared Phase 2B wire shape
//!
//! All shared fields now align: `summary`, `artifact_refs`, and
//! `rollup_id` / `evidence_rollup_id` (resolved via serde alias).
//! Python carries additional fields (`task_id`, `evidence_refs`,
//! `conclusion`, `trace_context`) that Rust also accepts; Rust carries
//! additional fields (`source_domain`, `evidence_count`, `delivery_id`)
//! that Python does not emit.

use limenet::contracts::{DeliveryPackage, DeliveryStatus, EvidenceRollup};
use std::fs;
use std::path::PathBuf;

fn wire_dir() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .unwrap()
        .join(".state")
        .join("artifacts")
        .join("delivery_wire")
}

fn read_wire_fixture(name: &str) -> String {
    let path = wire_dir().join(name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {path:?}: {e}"))
}

fn read_wire_fixture_value(name: &str) -> serde_json::Value {
    let text = read_wire_fixture(name);
    serde_json::from_str(&text).expect("fixture must be valid JSON")
}

// ---------------------------------------------------------------------------
// DeliveryStatus enum alignment — the shared contract surface
// ---------------------------------------------------------------------------

/// Extract the `delivery_status` string from a Python-emitted package JSON.
fn extract_delivery_status(fixture_name: &str) -> String {
    let v: serde_json::Value = read_wire_fixture_value(fixture_name);
    v["delivery_status"]
        .as_str()
        .unwrap_or("")
        .to_string()
}

#[test]
fn test_delivery_status_proposed_deserializes() {
    let status_str = extract_delivery_status("package_proposed.json");
    assert_eq!(status_str, "proposed");
    let status: DeliveryStatus =
        serde_json::from_str(&format!("\"{status_str}\"")).expect("proposed must deserialize");
    assert_eq!(status, DeliveryStatus::Proposed);
}

#[test]
fn test_delivery_status_accepted_deserializes() {
    let status_str = extract_delivery_status("package_accepted.json");
    assert_eq!(status_str, "accepted");
    let status: DeliveryStatus = serde_json::from_str(&format!("\"{status_str}\""))
        .expect("accepted must deserialize");
    assert_eq!(status, DeliveryStatus::Accepted);
}

#[test]
fn test_delivery_status_needs_revision_deserializes() {
    let status_str = extract_delivery_status("package_needs-revision.json");
    assert_eq!(status_str, "needs_revision");
    let status: DeliveryStatus = serde_json::from_str(&format!("\"{status_str}\""))
        .expect("needs_revision must deserialize");
    assert_eq!(status, DeliveryStatus::NeedsRevision);
}

#[test]
fn test_delivery_status_rejected_deserializes() {
    let status_str = extract_delivery_status("package_rejected.json");
    assert_eq!(status_str, "rejected");
    let status: DeliveryStatus =
        serde_json::from_str(&format!("\"{status_str}\"")).expect("rejected must deserialize");
    assert_eq!(status, DeliveryStatus::Rejected);
}

#[test]
fn test_delivery_status_superseded_deserializes() {
    let status_str = extract_delivery_status("package_superseded.json");
    assert_eq!(status_str, "superseded");
    let status: DeliveryStatus =
        serde_json::from_str(&format!("\"{status_str}\"")).expect("superseded must deserialize");
    assert_eq!(status, DeliveryStatus::Superseded);
}

#[test]
fn test_all_5_delivery_status_variants_align() {
    let cases = [
        ("package_proposed.json", DeliveryStatus::Proposed),
        ("package_accepted.json", DeliveryStatus::Accepted),
        ("package_needs-revision.json", DeliveryStatus::NeedsRevision),
        ("package_rejected.json", DeliveryStatus::Rejected),
        ("package_superseded.json", DeliveryStatus::Superseded),
    ];
    for (fixture, expected) in &cases {
        let status_str = extract_delivery_status(fixture);
        let status: DeliveryStatus =
            serde_json::from_str(&format!("\"{status_str}\"")).unwrap_or_else(|e| {
                panic!("{fixture}: delivery_status '{status_str}' must deserialize: {e}")
            });
        assert_eq!(
            status, *expected,
            "{fixture}: expected {expected:?}, got {status:?}"
        );
    }
}

#[test]
fn test_delivery_status_try_from_all_5_variants() {
    for text in &["proposed", "accepted", "needs_revision", "rejected", "superseded"] {
        let status = DeliveryStatus::try_from(*text)
            .unwrap_or_else(|e| panic!("try_from({text}) must succeed: {e}"));
        let roundtrip = serde_json::to_string(&status).unwrap();
        assert_eq!(roundtrip, format!("\"{text}\""));
    }
}

// ---------------------------------------------------------------------------
// Python DeliveryPackage → Rust DeliveryPackage deserialization (shared wire)
// ---------------------------------------------------------------------------

/// The Python DeliveryPackage JSON deserializes as a Rust DeliveryPackage
/// now that both repos share the same Phase 2B wire field names.
#[test]
fn test_python_delivery_package_deserializes_in_rust() {
    let json = read_wire_fixture("package_proposed.json");
    let pkg: DeliveryPackage =
        serde_json::from_str(&json).expect("Python DeliveryPackage must deserialize in Rust");
    assert!(pkg.package_id.is_some());
    assert!(pkg.delivery_contract_id.is_some());
    assert!(pkg.delivery_status.is_some());
}

/// The minimal DeliveryPackage fixture also deserializes correctly.
#[test]
fn test_python_minimal_package_deserializes() {
    let json = read_wire_fixture("package_minimal.json");
    let pkg: DeliveryPackage =
        serde_json::from_str(&json).expect("Python minimal DeliveryPackage must deserialize");
    assert!(pkg.package_id.is_some());
    assert!(pkg.delivery_contract_id.is_some());
}

/// All 6 Python-emitted packages deserialize successfully in Rust.
#[test]
fn test_all_6_python_packages_deserialize_in_rust() {
    let fixtures = [
        "package_proposed.json",
        "package_accepted.json",
        "package_needs-revision.json",
        "package_rejected.json",
        "package_superseded.json",
        "package_minimal.json",
    ];
    for name in &fixtures {
        let json = read_wire_fixture(name);
        let result: Result<DeliveryPackage, _> = serde_json::from_str(&json);
        assert!(
            result.is_ok(),
            "{name}: Python DeliveryPackage must deserialize in Rust"
        );
    }
}

/// All 6 Python-emitted packages validate under Rust rules.
#[test]
fn test_all_6_python_packages_validate() {
    let fixtures = [
        "package_proposed.json",
        "package_accepted.json",
        "package_needs-revision.json",
        "package_rejected.json",
        "package_superseded.json",
        "package_minimal.json",
    ];
    for name in &fixtures {
        let json = read_wire_fixture(name);
        let pkg: DeliveryPackage =
            serde_json::from_str(&json).unwrap_or_else(|e| panic!("{name} must deserialize: {e}"));
        assert!(
            pkg.validate().is_ok(),
            "{name}: Python DeliveryPackage must validate under Rust rules"
        );
    }
}

/// The delivery_contract_id field anchors the package to the delegation
/// contract, and the shared key name is preserved across repos.
#[test]
fn test_delivery_contract_id_anchors_across_repos() {
    let json = read_wire_fixture("package_accepted.json");
    let pkg: DeliveryPackage =
        serde_json::from_str(&json).expect("must deserialize");
    assert_eq!(
        pkg.delivery_contract_id.as_deref(),
        Some("dc-int2b-005-g-001"),
        "delivery_contract_id must match the shared delegation contract anchor"
    );
}

// ---------------------------------------------------------------------------
// Python EvidenceRollup → Rust EvidenceRollup deserialization (partial overlap)
// ---------------------------------------------------------------------------

/// The `summary` field is the primary shared field between Python and Rust
/// EvidenceRollup structs.  It deserializes correctly from Python-emitted JSON.
#[test]
fn test_evidence_rollup_summary_deserializes() {
    let json = read_wire_fixture("rollup_standard.json");
    let rollup: EvidenceRollup =
        serde_json::from_str(&json).expect("rollup standard must deserialize");
    assert_eq!(
        rollup.summary.as_deref(),
        Some("Worker completed all acceptance criteria; no large payloads inlined.")
    );
}

/// The `artifact_refs` field is also shared between Python and Rust.
/// It deserializes correctly from Python-emitted JSON.
#[test]
fn test_evidence_rollup_artifact_refs_deserializes() {
    let json = read_wire_fixture("rollup_artifact-heavy.json");
    let rollup: EvidenceRollup =
        serde_json::from_str(&json).expect("rollup artifact-heavy must deserialize");
    let refs = rollup
        .artifact_refs
        .expect("artifact_refs must be present");
    assert_eq!(refs.len(), 5);
    assert!(refs.iter().all(|a| a.starts_with("artifacts/")));
}

/// Python's `rollup_id` key now correctly maps to Rust's `evidence_rollup_id`
/// field via the `#[serde(alias = "rollup_id")]` attribute.  The former
/// key-name mismatch is resolved — both repos can emit either key and
/// deserialization succeeds.
#[test]
fn test_evidence_rollup_id_alias_resolves_key_mismatch() {
    let json = read_wire_fixture("rollup_standard.json");
    let rollup: EvidenceRollup =
        serde_json::from_str(&json).expect("rollup standard must deserialize");
    // Python emits "rollup_id" — the alias maps it to evidence_rollup_id
    assert_eq!(
        rollup.evidence_rollup_id.as_deref(),
        Some("er-int2b-005-001"),
        "Python 'rollup_id' must map to Rust 'evidence_rollup_id' via serde alias"
    );
    // The original key is still present in the raw JSON
    let v: serde_json::Value = serde_json::from_str(&json).unwrap();
    assert_eq!(v["rollup_id"].as_str(), Some("er-int2b-005-001"));
}

/// The summary-only rollup has empty artifact_refs — shared field preserves
/// the empty list semantics.
#[test]
fn test_summary_only_rollup_deserializes() {
    let json = read_wire_fixture("rollup_summary-only.json");
    let rollup: EvidenceRollup =
        serde_json::from_str(&json).expect("rollup summary-only must deserialize");
    assert_eq!(
        rollup.summary.as_deref(),
        Some("Minimal summary with no artifacts or evidence refs.")
    );
    // Python emits empty artifact_refs, Rust deserializes as Some(vec![])
    let refs = rollup.artifact_refs.expect("artifact_refs must be present");
    assert!(refs.is_empty());
}

/// All 3 Python-emitted EvidenceRollup fixtures deserialize successfully
/// as Rust EvidenceRollup structs (extra keys ignored, missing keys become None).
#[test]
fn test_all_3_python_rollups_deserialize() {
    let fixtures = [
        "rollup_standard.json",
        "rollup_summary-only.json",
        "rollup_artifact-heavy.json",
    ];
    for name in &fixtures {
        let json = read_wire_fixture(name);
        let rollup: EvidenceRollup = serde_json::from_str(&json)
            .unwrap_or_else(|e| panic!("{name} must deserialize as Rust EvidenceRollup: {e}"));
        // All three must validate under Rust rules
        if let Err(e) = rollup.validate() {
            panic!("{name} must validate under Rust rules: {e}");
        }
    }
}

// ---------------------------------------------------------------------------
// Python EvidenceRollup → Rust validation tests
// ---------------------------------------------------------------------------

/// Python rollup fields that Rust does not have (task_id, evidence_refs,
/// conclusion, trace_context) are silently ignored during deserialization.
/// Rust fields that Python does not emit (source_domain, evidence_count,
/// delivery_id) become None.  This is correct behavior — neither side
/// requires the other's extra fields.
#[test]
fn test_rust_extra_fields_are_none_in_python_rollups() {
    let json = read_wire_fixture("rollup_standard.json");
    let rollup: EvidenceRollup = serde_json::from_str(&json).unwrap();
    assert!(rollup.source_domain.is_none(), "Python does not emit source_domain");
    assert!(rollup.evidence_count.is_none(), "Python does not emit evidence_count");
    assert!(rollup.delivery_id.is_none(), "Python does not emit delivery_id");
}

/// Python extra fields are preserved in the raw JSON but ignored by Rust.
#[test]
fn test_python_extra_fields_present_in_raw_json() {
    let json = read_wire_fixture("rollup_standard.json");
    let v: serde_json::Value = serde_json::from_str(&json).unwrap();
    // Python-only fields present in JSON
    assert!(v["task_id"].is_string(), "Python task_id must be in raw JSON");
    assert!(v["evidence_refs"].is_array(), "Python evidence_refs must be in raw JSON");
    assert!(v["conclusion"].is_string(), "Python conclusion must be in raw JSON");
    assert!(v["trace_context"].is_object(), "Python trace_context must be in raw JSON");
}

// ---------------------------------------------------------------------------
// Frozen delivery fixture roundtrip
// ---------------------------------------------------------------------------

/// The frozen delivery_package.json contains the canonical Python shape.
/// It deserializes and validates successfully in Rust.
#[test]
fn test_frozen_delivery_package_deserializes_and_validates() {
    let json = read_wire_fixture("frozen_delivery_package.json");
    let pkg: DeliveryPackage =
        serde_json::from_str(&json).expect("frozen delivery_package.json must deserialize");
    assert!(pkg.validate().is_ok(), "frozen delivery_package.json must validate");
}

/// The frozen evidence_rollup.json deserializes correctly (partial overlap).
#[test]
fn test_frozen_evidence_rollup_deserializes() {
    let json = read_wire_fixture("frozen_evidence_rollup.json");
    let rollup: EvidenceRollup =
        serde_json::from_str(&json).expect("frozen evidence rollup must deserialize");
    assert!(rollup.summary.is_some());
    assert!(rollup.artifact_refs.is_some());
    assert!(rollup.validate().is_ok());
}

/// The frozen delivery_proposal.json is a composite of 4 sub-documents.
/// Each sub-document is tested independently.
#[test]
fn test_frozen_delivery_proposal_structure() {
    let json = read_wire_fixture("frozen_delivery_proposal.json");
    let v: serde_json::Value = serde_json::from_str(&json).unwrap();
    assert!(v["ownership_record"].is_object());
    assert!(v["delegation_contract"].is_object());
    assert!(v["delivery_package"].is_object());
    assert!(v["evidence_rollup"].is_object());
}

// ---------------------------------------------------------------------------
// DeliveryStatus validate_status — structured error for cross-repo comparison
// ---------------------------------------------------------------------------

#[test]
fn test_validate_status_all_5_python_variants() {
    for status_str in &["proposed", "accepted", "needs_revision", "rejected", "superseded"] {
        let result = DeliveryStatus::validate_status(status_str);
        assert!(
            result.is_ok(),
            "validate_status({status_str}) must succeed for Python-emitted status"
        );
    }
}

#[test]
fn test_validate_status_rejects_unknown() {
    for bogus in &["pending", "cancelled", "in_review", "completed", ""] {
        let err = DeliveryStatus::validate_status(bogus).unwrap_err();
        assert_eq!(err.error, "validation_failed");
        assert_eq!(err.reason, "unsupported_status");
        assert_eq!(err.value.as_deref(), Some(*bogus));
    }
}

// ---------------------------------------------------------------------------
// Baseline package count verification
// ---------------------------------------------------------------------------

#[test]
fn test_all_6_package_fixtures_present() {
    let v: serde_json::Value = read_wire_fixture_value("all_baseline_packages.json");
    let arr = v.as_array().expect("all_baseline_packages must be a JSON array");
    assert_eq!(arr.len(), 6, "expected 6 baseline packages");
}

#[test]
fn test_all_3_rollup_fixtures_present() {
    let v: serde_json::Value = read_wire_fixture_value("all_baseline_rollups.json");
    let arr = v.as_array().expect("all_baseline_rollups must be a JSON array");
    assert_eq!(arr.len(), 3, "expected 3 baseline rollups");
}
