//! Cross-repo delegation wire-format integration tests.
//!
//! These tests verify that LimeNet's `DelegationContract` can deserialize
//! JSON emitted by the meta-agent Python `delegation_contract_asdict()`
//! exporter, and that the resulting contracts validate or produce the
//! expected structured errors.
//!
//! The JSON fixtures live in `.state/artifacts/delegation_wire/` and are
//! generated by `.state/artifacts/export_delegation_fixtures.py`.

use limenet::contracts::DelegationContract;
use std::fs;
use std::path::PathBuf;

fn wire_dir() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .unwrap()
        .join(".state")
        .join("artifacts")
        .join("delegation_wire")
}

fn read_wire_fixture(name: &str) -> String {
    let path = wire_dir().join(name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {path:?}: {e}"))
}

// ---------------------------------------------------------------------------
// Deserialization tests — can LimeNet parse Python-emitted JSON?
// ---------------------------------------------------------------------------

#[test]
fn test_deserialize_all_meta_agent_contracts() {
    let json = read_wire_fixture("all_baseline_contracts.json");
    let contracts: Vec<DelegationContract> =
        serde_json::from_str(&json).expect("all baseline contracts must deserialize");
    assert_eq!(contracts.len(), 6, "expected 6 baseline contracts");
}

#[test]
fn test_deserialize_private_full_strict() {
    let json = read_wire_fixture("private-full-strict.json");
    let c: DelegationContract =
        serde_json::from_str(&json).expect("private-full-strict must deserialize");
    // identity anchor fields are empty strings in Python → Some("") in Rust
    assert_eq!(c.delegation_id.as_deref(), Some(""));
    assert_eq!(c.upstream_work_request_id.as_deref(), Some(""));
    assert_eq!(c.upstream_task_id.as_deref(), Some(""));
    assert_eq!(c.upstream_backend_id.as_deref(), Some(""));
    assert_eq!(c.downstream_domain_kind, "");
    assert_eq!(c.downstream_graph_id.as_deref(), Some(""));
}

#[test]
fn test_deserialize_full_anchors() {
    let json = read_wire_fixture("full-anchors.json");
    let c: DelegationContract =
        serde_json::from_str(&json).expect("full-anchors must deserialize");
    assert_eq!(c.delegation_id.as_deref(), Some("dg-int2b-003-g-006"));
    assert_eq!(
        c.upstream_work_request_id.as_deref(),
        Some("wr-int2b-003-g-006")
    );
    assert_eq!(c.upstream_task_id.as_deref(), Some("T-int2b-003-g-006"));
    assert_eq!(c.upstream_backend_id.as_deref(), Some("limenet-prod"));
    assert_eq!(c.downstream_domain_kind, "meta-agent");
    assert_eq!(
        c.downstream_graph_id.as_deref(),
        Some("graph-int2b-003-g-006")
    );
}

#[test]
fn test_deserialize_upstream_only() {
    let json = read_wire_fixture("upstream-only.json");
    let c: DelegationContract =
        serde_json::from_str(&json).expect("upstream-only must deserialize");
    assert_eq!(c.upstream_backend_id.as_deref(), Some("limenet-prod"));
    assert_eq!(
        c.upstream_work_request_id.as_deref(),
        Some("wr-int2b-003-g-004")
    );
    // empty-string downstream fields become Some("") not None
    assert_eq!(c.downstream_graph_id.as_deref(), Some(""));
}

#[test]
fn test_deserialize_downstream_only() {
    let json = read_wire_fixture("downstream-only.json");
    let c: DelegationContract =
        serde_json::from_str(&json).expect("downstream-only must deserialize");
    assert_eq!(c.downstream_domain_kind, "meta-agent");
    assert_eq!(
        c.downstream_graph_id.as_deref(),
        Some("graph-int2b-003-g-005")
    );
    // empty-string upstream fields become Some("")
    assert_eq!(c.upstream_backend_id.as_deref(), Some(""));
}

// ---------------------------------------------------------------------------
// Validation tests — do Python-emitted contracts validate under Rust rules?
// ---------------------------------------------------------------------------

/// Contracts with fully-populated identity anchors (full-anchors,
/// downstream-only) should validate cleanly under LimeNet rules.
#[test]
fn test_full_anchors_validates() {
    let json = read_wire_fixture("full-anchors.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    assert!(
        c.validate().is_ok(),
        "full-anchors must validate under LimeNet rules"
    );
}

#[test]
fn test_downstream_only_validates() {
    let json = read_wire_fixture("downstream-only.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    assert!(
        c.validate().is_ok(),
        "downstream-only must validate under LimeNet rules"
    );
}

/// Contracts with empty-string identity anchors fail LimeNet validation
/// because "" becomes Some("") rather than None, triggering the downstream
/// domain_kind non-emptiness check.
///
/// This is a documented wire-format gap (GAP-DEL-01): Python uses empty
/// strings for "not set" while Rust uses Option::None.  When Python emits
/// `"downstream_graph_id": ""`, Rust sees `Some("")` and then rejects the
/// contract because `downstream_domain_kind` is also empty.
#[test]
fn test_private_full_strict_rejected_by_lime_net() {
    let json = read_wire_fixture("private-full-strict.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    let err = c.validate().unwrap_err();
    assert!(
        err.contains("downstream_domain_kind"),
        "expected downstream_domain_kind error for empty-string identity anchors, got: {err}"
    );
}

#[test]
fn test_public_full_loose_rejected_by_lime_net() {
    let json = read_wire_fixture("public-full-loose.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    let err = c.validate().unwrap_err();
    assert!(
        err.contains("downstream_domain_kind"),
        "expected downstream_domain_kind error for empty-string identity anchors, got: {err}"
    );
}

#[test]
fn test_shared_none_passthrough_rejected_by_lime_net() {
    let json = read_wire_fixture("shared-none-passthrough.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    let err = c.validate().unwrap_err();
    assert!(
        err.contains("downstream_domain_kind"),
        "expected downstream_domain_kind error for empty-string identity anchors, got: {err}"
    );
}

#[test]
fn test_upstream_only_rejected_by_lime_net() {
    let json = read_wire_fixture("upstream-only.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    let err = c.validate().unwrap_err();
    assert!(
        err.contains("downstream_domain_kind"),
        "upstream-only has empty downstream_graph_id which triggers domain_kind check, got: {err}"
    );
}

// ---------------------------------------------------------------------------
// Structured validation error tests
// ---------------------------------------------------------------------------

#[test]
fn test_structured_error_for_empty_anchor_contract() {
    let json = read_wire_fixture("private-full-strict.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    let err = c.validate_structured().unwrap_err();
    assert_eq!(err.error, "validation_failed");
    assert_eq!(err.reason, "empty_field");
    assert_eq!(err.field.as_deref(), Some("downstream_domain_kind"));
    assert_eq!(err.anchor.as_deref(), Some("downstream"));
}

// ---------------------------------------------------------------------------
// Frozen fixture roundtrip — the canonical delegation_contract.json
// ---------------------------------------------------------------------------

#[test]
fn test_frozen_fixture_deserializes() {
    let json = read_wire_fixture("frozen_delegation_contract.json");
    let c: DelegationContract =
        serde_json::from_str(&json).expect("frozen fixture must deserialize");
    assert_eq!(c.delegation_id.as_deref(), Some("dg-P2B-002-g-001"));
    assert_eq!(c.downstream_domain_kind, "meta-agent");
}

#[test]
fn test_frozen_fixture_validates() {
    let json = read_wire_fixture("frozen_delegation_contract.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    assert!(
        c.validate().is_ok(),
        "frozen delegation fixture must validate under LimeNet rules"
    );
}
