#![cfg(feature = "cross-repo-fixtures")]

//! Cross-repo delegation wire-format integration tests.
//!
//! These tests verify that LimeNet's `DelegationContract` can deserialize
//! JSON emitted by the meta-agent Python `delegation_contract_asdict()`
//! exporter, and that the resulting contracts validate or produce the
//! expected structured errors.
//!
//! The JSON fixtures live in `.state/artifacts/delegation_wire/` and are
//! generated by `.state/artifacts/export_delegation_fixtures.py`.
//!
//! ## GAP-DEL-01 resolution
//!
//! Python uses empty strings (`""`) for unset optional identity anchors.
//! LimeNet's custom `deserialize_empty_string_as_none` maps those empty
//! strings to `Option::None` so that contracts with sparse identity anchors
//! validate cleanly on the Rust side.

use limenet::contracts::DelegationContract;
use std::fs;
use std::path::PathBuf;

fn wire_dir() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
    .parent()
    .unwrap()
        .join(".state")
        .join("artifacts")
        .join("delegation_wire")
}

fn read_wire_fixture(name: &str) -> String {
    let path = wire_dir().join(name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {path:?}: {e}"))
}

// ---------------------------------------------------------------------------
// Deserialization tests — can LimeNet parse Python-emitted JSON?
// ---------------------------------------------------------------------------

#[test]
fn test_deserialize_all_meta_agent_contracts() {
    let json = read_wire_fixture("all_baseline_contracts.json");
    let contracts: Vec<DelegationContract> =
        serde_json::from_str(&json).expect("all baseline contracts must deserialize");
    assert_eq!(contracts.len(), 6, "expected 6 baseline contracts");
}

#[test]
fn test_deserialize_private_full_strict() {
    let json = read_wire_fixture("private-full-strict.json");
    let c: DelegationContract =
        serde_json::from_str(&json).expect("private-full-strict must deserialize");
    // Empty-string identity anchors from Python are mapped to None
    assert!(c.delegation_id.is_none(), "empty delegation_id must become None");
    assert!(c.upstream_work_request_id.is_none(), "empty upstream_work_request_id must become None");
    assert!(c.upstream_task_id.is_none(), "empty upstream_task_id must become None");
    assert!(c.upstream_backend_id.is_none(), "empty upstream_backend_id must become None");
    assert_eq!(c.downstream_domain_kind, "");
    assert!(c.downstream_graph_id.is_none(), "empty downstream_graph_id must become None");
    // Core policy fields are always present in Python baseline
    assert!(c.visibility_policy.is_some());
    assert!(c.evidence_rollup_policy.is_some());
    assert!(c.status_mapping_policy.is_some());
}

#[test]
fn test_deserialize_full_anchors() {
    let json = read_wire_fixture("full-anchors.json");
    let c: DelegationContract =
        serde_json::from_str(&json).expect("full-anchors must deserialize");
    assert_eq!(c.delegation_id.as_deref(), Some("dg-int2b-003-g-006"));
    assert_eq!(
        c.upstream_work_request_id.as_deref(),
        Some("wr-int2b-003-g-006")
    );
    assert_eq!(c.upstream_task_id.as_deref(), Some("T-int2b-003-g-006"));
    assert_eq!(c.upstream_backend_id.as_deref(), Some("limenet-prod"));
    assert_eq!(c.downstream_domain_kind, "meta-agent");
    assert_eq!(
        c.downstream_graph_id.as_deref(),
        Some("graph-int2b-003-g-006")
    );
}

#[test]
fn test_deserialize_upstream_only() {
    let json = read_wire_fixture("upstream-only.json");
    let c: DelegationContract =
        serde_json::from_str(&json).expect("upstream-only must deserialize");
    assert_eq!(c.upstream_backend_id.as_deref(), Some("limenet-prod"));
    assert_eq!(
        c.upstream_work_request_id.as_deref(),
        Some("wr-int2b-003-g-004")
    );
    // Empty-string downstream fields are mapped to None
    assert!(c.downstream_graph_id.is_none(), "empty downstream_graph_id must become None");
}

#[test]
fn test_deserialize_downstream_only() {
    let json = read_wire_fixture("downstream-only.json");
    let c: DelegationContract =
        serde_json::from_str(&json).expect("downstream-only must deserialize");
    assert_eq!(c.downstream_domain_kind, "meta-agent");
    assert_eq!(
        c.downstream_graph_id.as_deref(),
        Some("graph-int2b-003-g-005")
    );
    // Empty-string upstream fields are mapped to None
    assert!(c.upstream_backend_id.is_none(), "empty upstream_backend_id must become None");
}

// ---------------------------------------------------------------------------
// Validation tests — do Python-emitted contracts validate under Rust rules?
// ---------------------------------------------------------------------------

/// Contracts with fully-populated identity anchors validate cleanly.
#[test]
fn test_full_anchors_validates() {
    let json = read_wire_fixture("full-anchors.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    assert!(
        c.validate().is_ok(),
        "full-anchors must validate under LimeNet rules"
    );
}

/// Contracts with downstream-only identity anchors validate cleanly.
#[test]
fn test_downstream_only_validates() {
    let json = read_wire_fixture("downstream-only.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    assert!(
        c.validate().is_ok(),
        "downstream-only must validate under LimeNet rules"
    );
}

/// Contracts with empty-string identity anchors now validate cleanly
/// because the custom deserializer maps "" → None (GAP-DEL-01).
#[test]
fn test_private_full_strict_validates() {
    let json = read_wire_fixture("private-full-strict.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    assert!(
        c.validate().is_ok(),
        "private-full-strict must validate after GAP-DEL-01 fix"
    );
}

#[test]
fn test_public_full_loose_validates() {
    let json = read_wire_fixture("public-full-loose.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    assert!(
        c.validate().is_ok(),
        "public-full-loose must validate after GAP-DEL-01 fix"
    );
}

#[test]
fn test_shared_none_passthrough_validates() {
    let json = read_wire_fixture("shared-none-passthrough.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    assert!(
        c.validate().is_ok(),
        "shared-none-passthrough must validate after GAP-DEL-01 fix"
    );
}

#[test]
fn test_upstream_only_validates() {
    let json = read_wire_fixture("upstream-only.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    assert!(
        c.validate().is_ok(),
        "upstream-only must validate after GAP-DEL-01 fix"
    );
}

// ---------------------------------------------------------------------------
// Policy-field coverage tests — every policy axis must be present
// ---------------------------------------------------------------------------

#[test]
fn test_all_policy_axes_present_in_baseline() {
    let json = read_wire_fixture("all_baseline_contracts.json");
    let contracts: Vec<DelegationContract> = serde_json::from_str(&json).unwrap();

    let visibilities: Vec<_> = contracts.iter().filter_map(|c| c.visibility_policy).collect();
    let evidence_policies: Vec<_> = contracts.iter().filter_map(|c| c.evidence_rollup_policy).collect();
    let status_policies: Vec<_> = contracts.iter().filter_map(|c| c.status_mapping_policy).collect();

    // Every contract in the baseline has all three policy fields set
    assert_eq!(
        visibilities.len(),
        contracts.len(),
        "every baseline contract must have a visibility_policy"
    );
    assert_eq!(
        evidence_policies.len(),
        contracts.len(),
        "every baseline contract must have an evidence_rollup_policy"
    );
    assert_eq!(
        status_policies.len(),
        contracts.len(),
        "every baseline contract must have a status_mapping_policy"
    );
}

#[test]
fn test_policy_variants_cover_all_combinations() {
    use limenet::contracts::{EvidenceRollupPolicy, StatusMappingPolicy, VisibilityPolicy};

    let json = read_wire_fixture("all_baseline_contracts.json");
    let contracts: Vec<DelegationContract> = serde_json::from_str(&json).unwrap();

    let visibilities: std::collections::HashSet<_> =
        contracts.iter().filter_map(|c| c.visibility_policy).collect();
    let evidence_policies: std::collections::HashSet<_> =
        contracts.iter().filter_map(|c| c.evidence_rollup_policy).collect();
    let status_policies: std::collections::HashSet<_> =
        contracts.iter().filter_map(|c| c.status_mapping_policy).collect();

    assert!(
        visibilities.contains(&VisibilityPolicy::Private),
        "baseline must cover private visibility"
    );
    assert!(
        visibilities.contains(&VisibilityPolicy::Public),
        "baseline must cover public visibility"
    );
    assert!(
        visibilities.contains(&VisibilityPolicy::Shared),
        "baseline must cover shared visibility"
    );

    assert!(
        evidence_policies.contains(&EvidenceRollupPolicy::None),
        "baseline must cover none evidence rollup"
    );
    assert!(
        evidence_policies.contains(&EvidenceRollupPolicy::Summary),
        "baseline must cover summary evidence rollup"
    );
    assert!(
        evidence_policies.contains(&EvidenceRollupPolicy::Full),
        "baseline must cover full evidence rollup"
    );

    assert!(
        status_policies.contains(&StatusMappingPolicy::Strict),
        "baseline must cover strict status mapping"
    );
    assert!(
        status_policies.contains(&StatusMappingPolicy::Loose),
        "baseline must cover loose status mapping"
    );
    assert!(
        status_policies.contains(&StatusMappingPolicy::Passthrough),
        "baseline must cover passthrough status mapping"
    );
}

// ---------------------------------------------------------------------------
// Structured validation error tests (still verify error shape for truly
// invalid contracts)
// ---------------------------------------------------------------------------

#[test]
fn test_structured_error_for_empty_domain_kind_with_graph_id() {
    // Manually construct a contract that has a graph_id but empty domain_kind
    let json = r#"{
        "downstream_domain_kind": "",
        "downstream_graph_id": "g-001"
    }"#;
    let c: DelegationContract = serde_json::from_str(json).unwrap();
    let err = c.validate_structured().unwrap_err();
    assert_eq!(err.error, "validation_failed");
    assert_eq!(err.reason, "empty_field");
    assert_eq!(err.field.as_deref(), Some("downstream_domain_kind"));
    assert_eq!(err.anchor.as_deref(), Some("downstream"));
}

// ---------------------------------------------------------------------------
// Frozen fixture roundtrip — the canonical delegation_contract.json
// ---------------------------------------------------------------------------

#[test]
fn test_frozen_fixture_deserializes() {
    let json = read_wire_fixture("frozen_delegation_contract.json");
    let c: DelegationContract =
        serde_json::from_str(&json).expect("frozen fixture must deserialize");
    assert_eq!(c.delegation_id.as_deref(), Some("dg-int2b-003-g-006"));
    assert_eq!(c.downstream_domain_kind, "meta-agent");
}

#[test]
fn test_frozen_fixture_validates() {
    let json = read_wire_fixture("frozen_delegation_contract.json");
    let c: DelegationContract = serde_json::from_str(&json).unwrap();
    assert!(
        c.validate().is_ok(),
        "frozen delegation fixture must validate under LimeNet rules"
    );
}
