#![cfg(feature = "cross-repo-fixtures")]

//! Cross-repo ownership wire-format integration tests.
//!
//! These tests validate that the mirror and promotion ownership guardrails
//! hold across the repo boundary: LimeNet (Rust) verifies that Python-emitted
//! ownership records from `meta-agent` carry the correct mode-specific
//! semantics and that the Rust-side `Ownership::validate_structured()`
//! enforces the same invariants as the Python-side
//! `assert_not_mirror_mode()` / `assert_has_promotion_intent()` guardrails.
//!
//! ## Guardrail 1 — mirror does not advance canonical state
//!
//! Mirror backends replicate the graph for read-only access.  Python enforces
//! this via `MirrorModeViolation`; Rust enforces it by rejecting mirror-mode
//! records that carry `promoted_from` (promotion lineage), and by requiring
//! `backend_kind` so the upstream source is identifiable.
//!
//! ## Guardrail 2 — promotion does not degenerate into dual-write
//!
//! Promotion-mode backends must declare a non-empty `promoted_from` lineage
//! reference before mutating state.  Python enforces this via
//! `PromotionModeViolation`; Rust enforces it by rejecting promotion-mode
//! records that omit `promoted_from`.
//!
//! ## Structural gaps documented here
//!
//! - **GAP-OWN-01** — Resolved: BackendKind enum vocabulary is now shared
//!   across Python and Rust (`json`, `local_limenet`, `remote_limenet`,
//!   `sqlite`, `postgres`).
//! - **GAP-OWN-02** — Resolved: OwnershipMode enum vocabulary is now shared
//!   across Python and Rust (`local_canonical`, `remote_canonical`,
//!   `mirror`, `promotion`).
//! - **GAP-OWN-03** — Empty-string vs Option::None for `promoted_from`:
//!   Python emits `"promoted_from": ""` for "not set"; Rust serde maps
//!   this to `Some("")`, triggering the mirror `invalid_transition` check
//!   that guards against reads that would advance canonical state.
//!
//! The JSON fixtures live in `.state/artifacts/ownership_wire/` and are
//! generated by the meta-agent fixture exporter.

use limenet::contracts::{BackendKind, Ownership, OwnershipMode};
use std::fs;
use std::path::PathBuf;

/// Resolve the wire fixture directory, checking multiple candidate locations.
///
/// Primary: `<repo-parent>/.state/artifacts/ownership_wire/` (full workspace)
/// Fallback: `<repo>/tests/fixtures/ownership_wire/` (OpenSandbox bundle)
fn wire_dir() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let primary = manifest_dir
        .parent()
        .unwrap()
        .join(".state")
        .join("artifacts")
        .join("ownership_wire");
    if primary.exists() {
        return primary;
    }
    manifest_dir.join("tests").join("fixtures").join("ownership_wire")
}

fn read_wire_fixture(name: &str) -> String {
    let path = wire_dir().join(name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {path:?}: {e}"))
}

fn read_wire_fixture_value(name: &str) -> serde_json::Value {
    let text = read_wire_fixture(name);
    serde_json::from_str(&text).expect("fixture must be valid JSON")
}

// ---------------------------------------------------------------------------
// Mirror guardrail — raw JSON field inspection
// ---------------------------------------------------------------------------

#[test]
fn test_mirror_original_ownership_mode_is_mirror() {
    let v = read_wire_fixture_value("mirror-original.json");
    assert_eq!(
        v["ownership_mode"].as_str(),
        Some("mirror"),
        "mirror-original must have ownership_mode=mirror"
    );
}

#[test]
fn test_mirror_original_promoted_from_is_empty() {
    let v = read_wire_fixture_value("mirror-original.json");
    assert_eq!(
        v["promoted_from"].as_str(),
        Some(""),
        "mirror-original must have empty promoted_from: mirror is read-only, no promotion lineage"
    );
}

#[test]
fn test_mirror_original_created_from_is_empty() {
    let v = read_wire_fixture_value("mirror-original.json");
    assert_eq!(
        v["created_from"].as_str(),
        Some(""),
        "mirror-original must have empty created_from: original mirror has no derived lineage"
    );
}

#[test]
fn test_mirror_derived_ownership_mode_is_mirror() {
    let v = read_wire_fixture_value("mirror-derived.json");
    assert_eq!(
        v["ownership_mode"].as_str(),
        Some("mirror"),
        "mirror-derived must have ownership_mode=mirror"
    );
}

#[test]
fn test_mirror_derived_promoted_from_is_empty() {
    let v = read_wire_fixture_value("mirror-derived.json");
    assert_eq!(
        v["promoted_from"].as_str(),
        Some(""),
        "mirror-derived must have empty promoted_from: even derived mirrors are read-only"
    );
}

#[test]
fn test_mirror_derived_has_created_from() {
    let v = read_wire_fixture_value("mirror-derived.json");
    assert_eq!(
        v["created_from"].as_str(),
        Some("parent-integration-graph"),
        "mirror-derived must reference the parent graph it was derived from"
    );
}

// ---------------------------------------------------------------------------
// Promotion guardrail — raw JSON field inspection
// ---------------------------------------------------------------------------

#[test]
fn test_promotion_transfer_ownership_mode_is_promotion() {
    let v = read_wire_fixture_value("promotion-transfer.json");
    assert_eq!(
        v["ownership_mode"].as_str(),
        Some("promotion"),
        "promotion-transfer must have ownership_mode=promotion"
    );
}

#[test]
fn test_promotion_transfer_has_promoted_from() {
    let v = read_wire_fixture_value("promotion-transfer.json");
    let promoted_from = v["promoted_from"].as_str().unwrap_or("");
    assert!(
        !promoted_from.is_empty(),
        "promotion-transfer must have non-empty promoted_from: promotion requires declared source"
    );
    assert_eq!(
        promoted_from, "/state/backends/legacy-sqlite",
        "promotion-transfer promoted_from must match the frozen legacy backend id"
    );
}

#[test]
fn test_promotion_transfer_created_from_is_empty() {
    let v = read_wire_fixture_value("promotion-transfer.json");
    assert_eq!(
        v["created_from"].as_str(),
        Some(""),
        "promotion-transfer must have empty created_from: original graph, not derived"
    );
}

#[test]
fn test_promotion_derived_transfer_ownership_mode_is_promotion() {
    let v = read_wire_fixture_value("promotion-derived-transfer.json");
    assert_eq!(
        v["ownership_mode"].as_str(),
        Some("promotion"),
        "promotion-derived-transfer must have ownership_mode=promotion"
    );
}

#[test]
fn test_promotion_derived_transfer_has_promoted_from() {
    let v = read_wire_fixture_value("promotion-derived-transfer.json");
    let promoted_from = v["promoted_from"].as_str().unwrap_or("");
    assert!(
        !promoted_from.is_empty(),
        "promotion-derived-transfer must have non-empty promoted_from: even derived promotions need declared source"
    );
}

#[test]
fn test_promotion_derived_transfer_has_created_from() {
    let v = read_wire_fixture_value("promotion-derived-transfer.json");
    assert_eq!(
        v["created_from"].as_str(),
        Some("parent-integration-graph"),
        "promotion-derived-transfer must have created_from for derived lineage"
    );
}

#[test]
fn test_promotion_transfer_promoted_from_differs_from_canonical_backend_id() {
    let v = read_wire_fixture_value("promotion-transfer.json");
    let promoted_from = v["promoted_from"].as_str().unwrap();
    let canonical = v["canonical_backend_id"].as_str().unwrap();
    assert_ne!(
        promoted_from, canonical,
        "promoted_from must differ from canonical_backend_id: cannot promote from own backend"
    );
}

// ---------------------------------------------------------------------------
// OwnershipMode enum alignment — shared values cross the boundary
// ---------------------------------------------------------------------------

#[test]
fn test_ownership_mode_mirror_deserializes_from_python() {
    // Python emits "mirror" — Rust OwnershipMode uses snake_case serde,
    // so "mirror" must deserialize as OwnershipMode::Mirror.
    let json = r#""mirror""#;
    let mode: OwnershipMode =
        serde_json::from_str(json).expect("'mirror' must deserialize as OwnershipMode::Mirror");
    assert_eq!(mode, OwnershipMode::Mirror);
}

#[test]
fn test_ownership_mode_promotion_deserializes_from_python() {
    let json = r#""promotion""#;
    let mode: OwnershipMode = serde_json::from_str(json)
        .expect("'promotion' must deserialize as OwnershipMode::Promotion");
    assert_eq!(mode, OwnershipMode::Promotion);
}

#[test]
fn test_ownership_mode_local_canonical_deserializes_from_python() {
    let json = r#""local_canonical""#;
    let mode: OwnershipMode = serde_json::from_str(json)
        .expect("'local_canonical' must deserialize as OwnershipMode::LocalCanonical");
    assert_eq!(mode, OwnershipMode::LocalCanonical);
}

#[test]
fn test_ownership_mode_remote_canonical_deserializes_from_python() {
    let json = r#""remote_canonical""#;
    let mode: OwnershipMode = serde_json::from_str(json)
        .expect("'remote_canonical' must deserialize as OwnershipMode::RemoteCanonical");
    assert_eq!(mode, OwnershipMode::RemoteCanonical);
}

#[test]
fn test_backend_kind_json_deserializes_from_python() {
    let json = r#""json""#;
    let kind: BackendKind = serde_json::from_str(json)
        .expect("'json' must deserialize as BackendKind::Json");
    assert_eq!(kind, BackendKind::Json);
}

#[test]
fn test_all_python_backend_kinds_deserialize_in_rust() {
    let cases = [
        ("json", BackendKind::Json),
        ("local_limenet", BackendKind::LocalLimenet),
        ("remote_limenet", BackendKind::RemoteLimenet),
        ("sqlite", BackendKind::Sqlite),
        ("postgres", BackendKind::Postgres),
    ];
    for (py_kind, expected) in &cases {
        let json = format!("\"{py_kind}\"");
        let kind: BackendKind = serde_json::from_str(&json)
            .unwrap_or_else(|e| panic!("{py_kind} must deserialize as BackendKind: {e}"));
        assert_eq!(kind, *expected);
    }
}

// ---------------------------------------------------------------------------
// Partial deserialization — shared ownership vocabulary survives the boundary
// ---------------------------------------------------------------------------

#[test]
fn test_mirror_fixture_partial_deserialize_ownership_mode_preserved() {
    let json = read_wire_fixture("mirror-original.json");
    let ownership: Ownership = serde_json::from_str(&json)
        .expect("mirror-original.json must partially deserialize as Ownership");
    assert_eq!(
        ownership.ownership_mode,
        Some(OwnershipMode::Mirror),
        "ownership_mode=mirror must survive cross-repo deserialization"
    );
}

#[test]
fn test_mirror_fixture_partial_deserialize_backend_kind_preserved() {
    let json = read_wire_fixture("mirror-original.json");
    let ownership: Ownership = serde_json::from_str(&json)
        .expect("mirror-original.json must partially deserialize as Ownership");
    assert!(
        ownership.backend_kind == Some(BackendKind::Json),
        "Python backend_kind 'json' must survive cross-repo deserialization"
    );
}

#[test]
fn test_promotion_fixture_partial_deserialize_ownership_mode_preserved() {
    let json = read_wire_fixture("promotion-transfer.json");
    let ownership: Ownership = serde_json::from_str(&json)
        .expect("promotion-transfer.json must partially deserialize as Ownership");
    assert_eq!(
        ownership.ownership_mode,
        Some(OwnershipMode::Promotion),
        "ownership_mode=promotion must survive cross-repo deserialization"
    );
}

#[test]
fn test_promotion_fixture_partial_deserialize_promoted_from_preserved() {
    let json = read_wire_fixture("promotion-transfer.json");
    let ownership: Ownership = serde_json::from_str(&json)
        .expect("promotion-transfer.json must partially deserialize as Ownership");
    assert_eq!(
        ownership.promoted_from.as_deref(),
        Some("/state/backends/legacy-sqlite"),
        "promoted_from must survive cross-repo deserialization from Python fixture"
    );
}

#[test]
fn test_promotion_derived_fixture_partial_deserialize_both_lineage_preserved() {
    let json = read_wire_fixture("promotion-derived-transfer.json");
    let ownership: Ownership = serde_json::from_str(&json)
        .expect("promotion-derived-transfer.json must partially deserialize as Ownership");
    assert_eq!(ownership.ownership_mode, Some(OwnershipMode::Promotion));
    assert_eq!(
        ownership.created_from.as_deref(),
        Some("parent-integration-graph")
    );
    assert_eq!(
        ownership.promoted_from.as_deref(),
        Some("/state/backends/legacy-sqlite")
    );
}

// ---------------------------------------------------------------------------
// GAP-OWN-03: Empty-string promoted_from in mirror fixtures
// ---------------------------------------------------------------------------

/// Python emits `"promoted_from": ""` for mirror records.  The custom
/// `deserialize_empty_as_none` normalizer maps this to `None` so that the
/// mirror `invalid_transition` guardrail does not produce a false positive.
///
/// GAP-OWN-03 is resolved for `promoted_from` and `created_from` at the
/// serde deserialization layer.
#[test]
fn test_mirror_fixture_empty_promoted_from_normalized_to_none() {
    let json = read_wire_fixture("mirror-original.json");
    let ownership: Ownership = serde_json::from_str(&json).unwrap();
    // Python emitted "" — normalizer maps it to None
    assert!(
        ownership.promoted_from.is_none(),
        "GAP-OWN-03 resolved: empty-string promoted_from is normalized to None"
    );
    assert!(
        ownership.created_from.is_none(),
        "GAP-OWN-03 resolved: empty-string created_from is normalized to None"
    );
    // Mirror mode is still correctly deserialized
    assert_eq!(ownership.ownership_mode, Some(OwnershipMode::Mirror));
    assert_eq!(ownership.backend_kind, Some(BackendKind::Json));
    assert!(ownership.validate_structured().is_ok());
}

#[test]
fn test_mirror_fixture_empty_promoted_from_valid_in_python_raw() {
    // The Python-side raw JSON proves the record is valid:
    // ownership_mode=mirror, promoted_from="" (semantically empty)
    let v = read_wire_fixture_value("mirror-original.json");
    assert_eq!(v["ownership_mode"].as_str(), Some("mirror"));
    assert!(
        v["promoted_from"].as_str() == Some("") || v["promoted_from"].is_null(),
        "promoted_from must be empty string or null (unset ancestry field)"
    );
    // On the Python side, validate_ownership_lineage accepts this because
    // the promoted_from check uses truthiness (bool("") is False).
    // The gap is purely at the Rust serde layer.
}

// ---------------------------------------------------------------------------
// Guardrail 1 — mirror read-only: Rust validate_structured enforcement
// ---------------------------------------------------------------------------

/// Mirror mode with valid backend_kind and no promoted_from passes validation.
#[test]
fn test_mirror_valid_passes_rust_validation() {
    let ownership = Ownership {
        ownership_mode: Some(OwnershipMode::Mirror),
        backend_kind: Some(BackendKind::Json),
        created_from: None,
        promoted_from: None,
    };
    let result = ownership.validate_structured();
    assert!(
        result.is_ok(),
        "mirror with backend_kind and no promoted_from must pass validation"
    );
}

/// Mirror mode without backend_kind is rejected — Rust requires the
/// upstream source to be identifiable for read-only mirrors.
#[test]
fn test_mirror_without_backend_kind_rejected() {
    let ownership = Ownership {
        ownership_mode: Some(OwnershipMode::Mirror),
        backend_kind: None,
        created_from: None,
        promoted_from: None,
    };
    let err = ownership.validate_structured().unwrap_err();
    assert_eq!(err.error, "validation_failed");
    assert_eq!(err.reason, "missing_field");
    assert_eq!(err.field.as_deref(), Some("backend_kind"));
    assert_eq!(err.ownership_mode.as_deref(), Some("mirror"));
}

/// Mirror mode with promotion lineage is rejected — mirror is read-only
/// and must not carry promotion state that would advance canonical state.
#[test]
fn test_mirror_with_promoted_from_rejected_invalid_transition() {
    let ownership = Ownership {
        ownership_mode: Some(OwnershipMode::Mirror),
        backend_kind: Some(BackendKind::LocalLimenet),
        created_from: None,
        promoted_from: Some("/state/backends/legacy-sqlite".to_string()),
    };
    let err = ownership.validate_structured().unwrap_err();
    assert_eq!(err.error, "validation_failed");
    assert_eq!(err.reason, "invalid_transition");
    assert_eq!(err.field.as_deref(), Some("promoted_from"));
    assert_eq!(err.ownership_mode.as_deref(), Some("mirror"));
}

/// Mirror mode with only created_from lineage passes — derived mirrors
/// are still read-only replicas.
#[test]
fn test_mirror_derived_without_promoted_from_passes() {
    let ownership = Ownership {
        ownership_mode: Some(OwnershipMode::Mirror),
        backend_kind: Some(BackendKind::RemoteLimenet),
        created_from: Some("parent-integration-graph".to_string()),
        promoted_from: None,
    };
    assert!(ownership.validate_structured().is_ok());
}

// ---------------------------------------------------------------------------
// Guardrail 2 — promotion no dual-write: Rust validate_structured enforcement
// ---------------------------------------------------------------------------

/// Promotion mode with non-empty promoted_from passes — the source is declared,
/// preventing implicit dual-write.
#[test]
fn test_promotion_with_promoted_from_passes() {
    let ownership = Ownership {
        ownership_mode: Some(OwnershipMode::Promotion),
        backend_kind: Some(BackendKind::Json),
        created_from: None,
        promoted_from: Some("/state/backends/legacy-sqlite".to_string()),
    };
    assert!(ownership.validate_structured().is_ok());
}

/// Promotion mode without promoted_from is rejected — this prevents
/// dual-write by requiring an explicit source declaration.
#[test]
fn test_promotion_without_promoted_from_rejected_missing_field() {
    let ownership = Ownership {
        ownership_mode: Some(OwnershipMode::Promotion),
        backend_kind: Some(BackendKind::Json),
        created_from: None,
        promoted_from: None,
    };
    let err = ownership.validate_structured().unwrap_err();
    assert_eq!(err.error, "validation_failed");
    assert_eq!(err.reason, "missing_field");
    assert_eq!(err.field.as_deref(), Some("promoted_from"));
    assert_eq!(err.ownership_mode.as_deref(), Some("promotion"));
}

/// Promotion mode with empty promoted_from is rejected — an empty
/// string is not a valid source declaration.
#[test]
fn test_promotion_with_empty_promoted_from_rejected() {
    let ownership = Ownership {
        ownership_mode: Some(OwnershipMode::Promotion),
        backend_kind: Some(BackendKind::Json),
        created_from: None,
        promoted_from: Some("".to_string()),
    };
    let err = ownership.validate_structured().unwrap_err();
    assert_eq!(err.reason, "empty_field");
    assert_eq!(err.field.as_deref(), Some("promoted_from"));
    assert_eq!(err.ownership_mode.as_deref(), Some("promotion"));
}

/// Promotion mode with whitespace-only promoted_from is also rejected.
#[test]
fn test_promotion_with_whitespace_promoted_from_rejected() {
    let ownership = Ownership {
        ownership_mode: Some(OwnershipMode::Promotion),
        backend_kind: Some(BackendKind::Json),
        created_from: None,
        promoted_from: Some("   ".to_string()),
    };
    let err = ownership.validate_structured().unwrap_err();
    assert_eq!(err.reason, "empty_field");
    assert_eq!(err.field.as_deref(), Some("promoted_from"));
}

// ---------------------------------------------------------------------------
// Promotion intent — explicit intent survives the boundary
// ---------------------------------------------------------------------------

/// The Python-emitted promotion_intent.json carries a full transfer intent
/// with source/target backend ids.  Verify the raw fields.
#[test]
fn test_promotion_intent_fixture_fields() {
    let v = read_wire_fixture_value("promotion_intent.json");
    assert_eq!(v["graph_id"].as_str(), Some("demo-project-graph"));
    assert_eq!(v["intent_type"].as_str(), Some("transfer"));
    assert_eq!(
        v["source_backend_id"].as_str(),
        Some("/state/graphs/demo-project")
    );
    assert_eq!(
        v["target_backend_id"].as_str(),
        Some("postgres://state/db/graphs")
    );
    assert_eq!(v["source_backend_kind"].as_str(), Some("json"));
    assert_eq!(v["target_backend_kind"].as_str(), Some("postgres"));
}

/// The promotion intent source and target backends differ — dual-write
/// is impossible because source ≠ target.
#[test]
fn test_promotion_intent_source_differs_from_target() {
    let v = read_wire_fixture_value("promotion_intent.json");
    let source = v["source_backend_id"].as_str().unwrap();
    let target = v["target_backend_id"].as_str().unwrap();
    assert_ne!(
        source, target,
        "promotion intent source and target backends must differ: sameness would imply dual-write"
    );
}

/// Promotion intent carries trace context for causation tracking.
#[test]
fn test_promotion_intent_has_trace_context() {
    let v = read_wire_fixture_value("promotion_intent.json");
    let tc = &v["trace_context"];
    assert_eq!(tc["correlation_id"].as_str(), Some("run-promotion-fixture-001"));
    assert_eq!(tc["task_id"].as_str(), Some("P2B-002-e"));
}

// ---------------------------------------------------------------------------
// Baseline completeness — all 7 records, mirror/promotion subsets
// ---------------------------------------------------------------------------

#[test]
fn test_all_baseline_records_contains_7_records() {
    let v = read_wire_fixture_value("all_baseline_records.json");
    let arr = v.as_array().expect("all_baseline_records must be a JSON array");
    assert_eq!(arr.len(), 7, "expected 7 baseline ownership records, got {}", arr.len());
}

#[test]
fn test_all_baseline_includes_2_mirror_records() {
    let v = read_wire_fixture_value("all_baseline_records.json");
    let arr = v.as_array().unwrap();
    let mirror_count = arr
        .iter()
        .filter(|r| r["ownership_mode"].as_str() == Some("mirror"))
        .count();
    assert_eq!(mirror_count, 2, "expected 2 mirror records in baseline");
}

#[test]
fn test_all_baseline_includes_2_promotion_records() {
    let v = read_wire_fixture_value("all_baseline_records.json");
    let arr = v.as_array().unwrap();
    let promo_count = arr
        .iter()
        .filter(|r| r["ownership_mode"].as_str() == Some("promotion"))
        .count();
    assert_eq!(promo_count, 2, "expected 2 promotion records in baseline");
}

#[test]
fn test_all_baseline_mirror_records_have_empty_promoted_from() {
    let v = read_wire_fixture_value("all_baseline_records.json");
    let arr = v.as_array().unwrap();
    for record in arr.iter().filter(|r| r["ownership_mode"].as_str() == Some("mirror")) {
        assert!(
            record["promoted_from"].as_str() == Some("") || record["promoted_from"].is_null(),
            "mirror record {} must have empty promoted_from",
            record["graph_id"].as_str().unwrap_or("?")
        );
    }
}

#[test]
fn test_all_baseline_promotion_records_have_nonempty_promoted_from() {
    let v = read_wire_fixture_value("all_baseline_records.json");
    let arr = v.as_array().unwrap();
    for record in arr.iter().filter(|r| r["ownership_mode"].as_str() == Some("promotion")) {
        let pf = record["promoted_from"].as_str().unwrap_or("");
        assert!(
            !pf.is_empty(),
            "promotion record {} must have non-empty promoted_from",
            record["graph_id"].as_str().unwrap_or("?")
        );
    }
}

// ---------------------------------------------------------------------------
// Frozen fixture roundtrip
// ---------------------------------------------------------------------------

#[test]
fn test_frozen_graph_ownership_record_deserializes() {
    let json = read_wire_fixture("frozen_graph_ownership_record.json");
    let v: serde_json::Value =
        serde_json::from_str(&json).expect("frozen fixture must be valid JSON");
    assert_eq!(v["graph_id"].as_str(), Some("mirror-integration-graph"));
    assert_eq!(v["ownership_mode"].as_str(), Some("mirror"));
}

// ---------------------------------------------------------------------------
// Delivery proposal composite — ownership record inside delivery proposal
// ---------------------------------------------------------------------------

/// The frozen delivery_proposal.json (in delivery_wire/) contains an
/// ownership_record sub-document.  Verify that it carries valid mirror
/// semantics.
#[test]
fn test_delivery_proposal_ownership_record_is_mirror() {
    let delivery_dir = {
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        manifest_dir
            .parent()
            .unwrap()
            .join(".state")
            .join("artifacts")
            .join("delivery_wire")
    };
    let path = delivery_dir.join("frozen_delivery_proposal.json");
    let json =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {path:?}: {e}"));
    let v: serde_json::Value =
        serde_json::from_str(&json).expect("frozen_delivery_proposal must be valid JSON");
    let own = &v["ownership_record"];
    assert_eq!(own["ownership_mode"].as_str(), Some("mirror"));
    assert!(
        own["promoted_from"].as_str() == Some("") || own["promoted_from"].is_null(),
        "promoted_from must be empty string or null (unset ancestry field)"
    );
}

// ---------------------------------------------------------------------------
// Concrete artifact references — each guardrail points to specific files
// ---------------------------------------------------------------------------

/// Smoke test verifying all ownership_wire fixtures exist on disk.
#[test]
fn test_all_ownership_wire_fixtures_exist() {
    let expected = [
        "all_baseline_records.json",
        "frozen_graph_ownership_record.json",
        "local-derived.json",
        "local-derived-promoted.json",
        "local-original.json",
        "mirror-derived.json",
        "mirror-original.json",
        "promotion-derived-transfer.json",
        "promotion_intent.json",
        "promotion-transfer.json",
    ];
    for name in &expected {
        let path = wire_dir().join(name);
        assert!(
            path.exists(),
            "ownership_wire fixture must exist: {name}"
        );
    }
}
